home:
    path: /
    controller: App\Controller\HomeController::index

extract_email_home:
    path: /extract_email_home
    controller: App\Controller\Email\EmailExtractorController::home

extract_email:
    path: /extract_email
    controller: App\Controller\Email\EmailExtractorController::extract